dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip
      - python

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.14.1/bazel-0.14.1-installer-linux-x86_64.sh
  - sha256sum -c .travis.bazel-0.14.1-installer-linux-x86_64.sh.sha256
  - bash bazel-0.14.1-installer-linux-x86_64.sh --user
  - openssl aes-256-cbc -K $encrypted_f41459709989_key -iv $encrypted_f41459709989_iv -in bio-routing-bazel.json.enc -out bio-routing-bazel.json -d

script:
- mkdir -p $HOME/gopath/src/github.com/bio-routing/
- ln -s $TRAVIS_BUILD_DIR $HOME/gopath/src/github.com/bio-routing/bio-rd || true
- cp .bazelrc.travis .bazelrc
- bazel coverage //...
- bazel build //vendor/github.com/q3k/goveralls
- bazel-bin/vendor/github.com/q3k/goveralls/linux_amd64_stripped/goveralls -coverprofile=$(find bazel-testlogs/ -iname coverage.dat -or -iname baseline_coverage.dat | paste -sd ',') -merge=false

